# Generated by Django 3.1.5 on 2021-01-22 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complemento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Polleria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo1', models.CharField(max_length=100)),
                ('tipo2', models.CharField(max_length=100)),
                ('complemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polleria.complemento')),
            ],
        ),
    ]
